openapi: 3.0.1
info:
  termsOfService: http://www.jelli.com/terms/
  contact:
    email: info@jelli.com
  license:
    name: proprietary
  version: "1.0"
servers:
- url: /api
  variables: {}
tags:
- name: envmgrs
  description: Environment Manager controller
- name: nexus
  description: Nexus controller
- name: projectdata
  description: Project Data controller
paths:
  /v1/buildWithParameter:
    post:
      tags:
      - envmgrs
      summary: Build Jenkins job with paramter
      operationId: buildWithParameter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvmgrEO'
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BuildStatus'
  /v1/projectdata/{project_key}:
    get:
      tags:
      - projectdata
      summary: get project data
      operationId: getProjectData
      parameters:
      - name: project_key
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDataEO'
  /v1/jobs:
    get:
      tags:
      - envmgrs
      summary: GET all jenkins jobs
      operationId: getJobs
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /v1/nexus/getArtifactNames:
    get:
      tags:
      - nexus
      summary: Returns a list of artifact names from Nexus
      operationId: getArtifactNames
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /v1/nexus/{artifactName}/getReleaseVersions:
    get:
      tags:
      - nexus
      summary: Returns a list of versions for the given artifact name
      operationId: getReleaseVersions
      parameters:
      - name: artifactName
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /v1/nexus/{artifactName}/getSnapshotVersions:
    get:
      tags:
      - nexus
      summary: Returns a list of snapshot versions for the given artifact name
      operationId: getSnapshotVersions
      parameters:
      - name: artifactName
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
  /v1/projectdata:
    get:
      tags:
      - projectdata
      summary: Get all records
      operationId: getAllRecords
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectsResponse'
    post:
      tags:
      - projectdata
      summary: Upsert project data
      operationId: upsertProjectData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDataEO'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDataEO'
                type: array
                items:
                  type: string
  /application.wadl:
    get:
      operationId: getWadl

  /v1/projectdata/{project_key}:
    get:
      tags:
      - projectdata
      summary: get project data
      operationId: getProjectData
      parameters:
      - name: project_key
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDataEO'
  /application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
                type: object
                additionalProperties:
                  type: string
  /v1/nexus/getArtifactNames:
    get:
      tags:
      - nexus
      summary: Returns a list of artifact names from Nexus
      operationId: getArtifactNames
      responses:
        default:
          description: default response
          content:
            application/xml: {}
  /application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          description: default response
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
components:
  schemas:
    BuildStatus:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: object
        completed:
          type: boolean
        success:
          type: boolean
        url:
          type: string
        url:
          type: string
        success:
          type: boolean
    EnvmgrEO:
      type: object
      properties:
        jobName:
          type: string
        hashMap:
          type: object
          additionalProperties:
            type: object
    KeyValue:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ObjectId:
      type: object
      properties:
        timestamp:
          type: integer
          format: int32
        date:
          type: string
          format: date-time
    ProjectDataEO:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ObjectId'
        projectKey:
          type: string
        friendlyName:
          type: string
        backendVersionEndpoint:
          type: string
        defaultLinkPattern:
          type: string
        linkOverrides:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        deploymentMetadata:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        onEnvDashboard:
          type: boolean
        landingEndpoint:
          type: string
        microserviceName:
          type: string
    ProjectsResponse:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/ProjectDataEO'
