version: '3.0'

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: jelli/mongodb:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: envmgr
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    logging:
      driver: local
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  envmgr:
    build:
      context: ../service
      dockerfile: Dockerfile
    image: jelli/envmgr:latest
    environment:
      - MONGODB_URI=mongodb
    restart: always
    ports:
      - "28888:28888"
      - "443:28888"
    depends_on:
      - mongodb
