openapi: 3.0.1
info:
  termsOfService: http://www.jelli.com/terms/
  contact:
    email: info@jelli.com
  license:
    name: proprietary
  version: "1.0"
servers:
- url: /api
  variables: {}
tags:
- name: envmgrs
  description: Environment Manager controller
paths:
  /v1/buildWithParameter:
    post:
      tags:
      - envmgrs
      summary: Build Jenkins job with paramter
      operationId: buildWithParameter
      parameters:
      - name: jobName
        in: query
        required: true
        schema:
          type: string
      - name: params
        in: query
        required: true
        schema:
          type: object
          additionalProperties:
            type: object
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BuildStatus'
  /v1/jobs:
    get:
      tags:
      - envmgrs
      summary: GET all jenkins jobs
      operationId: getJobs
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          description: default response
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
  /application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/xml: {}
components:
  schemas:
    BuildStatus:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: object
        url:
          type: string
        completed:
          type: boolean
        success:
          type: boolean
