spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - @jelli.docker.image.kafka.alias@:9092
          auto-create-topics: true
          auto-add-partitions: true
          min-partition-count: 1
          health-timeout: 2
          configuration:
            max:
              block:
                ms: 3000
